// Language translations and language switching logic
export const translations = {
    hi: {
        reverseTitle: '🔄 उल्टा सवाल',
        reverseDesc: 'जैसे: 60 = 12 × ? सही उत्तर दें (5 मिनट में जितने हो सकें)',
        reverseBtn: 'खेल शुरू करें',
        reverseGameTitle: '🔄 उल्टा सवाल',
        reverseInstructions: 'आपको उत्तर देना है: 12 × ? = (दिया गया उत्तर)। 5 मिनट में जितने हो सकें!',
        reverseStart: 'खेल शुरू करें',
        reverseSubmit: 'जवाब भेजें',
        title: "12 का पहाड़ा सीखें",
        subtitle: "मजेदार खेलों के साथ गुणा सीखें!",
        chartTitle: "📚 पहाड़े की तालिका",
        chartDesc: "12 का पूरा पहाड़ा देखें और याद करें",
        chartBtn: "तालिका देखें",
        quizTitle: "⚡ तेज़ प्रश्नोत्तरी",
        quizDesc: "60 सेकंड में जितने हो सके उतने सवालों के जवाब दें!",
        quizBtn: "क्विज़ शुरू करें",
        memoryTitle: "🧠 याददाश्त का खेल",
        memoryDesc: "गुणा के सवाल और उनके जवाब को मिलाएं",
        memoryBtn: "खेल शुरू करें",
        racingTitle: "🏎️ रेसिंग चुनौती",
        racingDesc: "सही जवाब देकर फिनिश लाइन तक पहुंचें!",
        racingBtn: "रेस शुरू करें",
        targetTitle: "🎯 निशाना अभ्यास",
        targetDesc: "गुणा के सवाल हल करके निशाना लगाएं",
        targetBtn: "अभ्यास शुरू करें",
        challengeTitle: "🌟 चुनौती मोड",
        challengeDesc: "1×12 से 12×12 तक के रैंडम सवाल",
        challengeBtn: "चुनौती लें",
    backBtn: "",
        tableChartTitle: "12 का पहाड़ा",
        tableInstructions: "नीचे दी गई तालिका को ध्यान से देखें और याद करने की कोशिश करें। प्रत्येक संख्या पर माउस रखने से वह बड़ी हो जाएगी।",
        quickFireTitle: "⚡ तेज़ प्रश्नोत्तरी",
        quickFireInstructions: "60 सेकंड में जितने हो सके उतने सवालों के जवाब दें। Enter दबाकर या Submit बटन दबाकर जवाब भेजें।",
        timer: "समय: 60 सेकंड",
        score: "स्कोर: 0",
        startMessage: "शुरू करने के लिए स्टार्ट दबाएं!",
        startQuiz: "क्विज़ शुरू करें",
        submitAnswer: "जवाब भेजें",
        memoryMatchTitle: "🧠 याददाश्त का खेल",
        memoryInstructions: "कार्ड पर क्लिक करें और गुणा के सवाल को उसके सही जवाब से मिलाएं। 6 जोड़े बनाने हैं।",
        matches: "जोड़े: 0/6",
        newGameBtn: "नया खेल",
        racingGameTitle: "🏎️ रेसिंग चुनौती",
        racingInstructions: "10 सवाल सही हल करके अपनी कार को फिनिश लाइन तक पहुंचाएं!",
        problemsSolved: "हल किए गए सवाल: 0/10",
        startRace: "रेस शुरू करें",
        submit: "भेजें",
        targetGameTitle: "🎯 निशाना अभ्यास",
        targetInstructions: "गुणा के सवाल हल करके निशाना लगाएं। आपकी सटीकता का हिसाब रखा जाएगा।",
        targetScore: "हिट: 0 | सटीकता: 0%",
        startPractice: "अभ्यास शुरू करें",
        fire: "गोली चलाएं! 🎯",
        challengeGameTitle: "🌟 चुनौती मोड",
        challengeInstructions: "यह सबसे कठिन मोड है! 1 से 12 तक के सभी पहाड़ों से सवाल आएंगे। गलत जवाब देने पर आपकी स्ट्रीक टूट जाएगी।",
        challengeScore: "स्ट्रीक: 0 | सर्वश्रेष्ठ: 0",
        startChallenge: "चुनौती शुरू करें",
        timeLeft: "समय:",
        seconds: "सेकंड",
        gameOver: "खेल समाप्त! अंतिम स्कोर:",
        playAgain: "फिर से खेलें",
        congratulations: "बधाई हो! आपने सभी जोड़े मिला लिए! 🎉",
        raceComplete: "रेस पूरी! आप जीत गए! 🏆",
        raceAgain: "फिर से रेस करें",
        wrongAnswer: "गलत जवाब! आपकी स्ट्रीक थी",
        tryAgain: "फिर कोशिश करें!",
        hits: "हिट:",
        accuracy: "सटीकता:",
        streak: "स्ट्रीक:",
        best: "सर्वश्रेष्ठ:"
    },
    en: {
        reverseTitle: '🔄 Reverse Quiz',
        reverseDesc: 'E.g.: 60 = 12 × ? Answer as many as you can in 5 minutes',
        reverseBtn: 'Start Game',
        reverseGameTitle: '🔄 Reverse Quiz',
        reverseInstructions: 'Answer: 12 × ? = (given number). As many as you can in 5 minutes!',
        reverseStart: 'Start Game',
        reverseSubmit: 'Submit',
        title: "🎯 Learn 12's Times Table 🎯",
        subtitle: "Master multiplication with fun interactive games!",
        chartTitle: "📚 Times Table Chart",
        chartDesc: "View and memorize the complete 12 times table",
        chartBtn: "View Chart",
        quizTitle: "⚡ Quick Fire Quiz",
        quizDesc: "Answer as many questions as possible in 60 seconds!",
        quizBtn: "Start Quiz",
        memoryTitle: "🧠 Memory Match",
        memoryDesc: "Match multiplication problems with their answers",
        memoryBtn: "Play Memory",
        racingTitle: "🏎️ Racing Challenge",
        racingDesc: "Race to the finish by solving problems correctly!",
        racingBtn: "Start Race",
        targetTitle: "🎯 Target Practice",
        targetDesc: "Hit the target by solving multiplication problems",
        targetBtn: "Start Practice",
        challengeTitle: "🌟 Challenge Mode",
        challengeDesc: "Random problems from 1×12 to 12×12",
        challengeBtn: "Take Challenge",
        backBtn: "← Back to Games",
        tableChartTitle: "12 Times Table Chart",
        tableInstructions: "Carefully observe the table below and try to memorize it. Hover over each item to see it highlighted.",
        quickFireTitle: "⚡ Quick Fire Quiz",
        quickFireInstructions: "Answer as many questions as possible in 60 seconds. Press Enter or click Submit to send your answer.",
        timer: "Time: 60s",
        score: "Score: 0",
        startMessage: "Click Start to begin!",
        startQuiz: "Start Quiz",
        submitAnswer: "Submit Answer",
        memoryMatchTitle: "🧠 Memory Match",
        memoryInstructions: "Click on cards to flip them and match multiplication problems with their correct answers. Make 6 pairs.",
        matches: "Matches: 0/6",
        newGameBtn: "New Game",
        racingGameTitle: "🏎️ Racing Challenge",
        racingInstructions: "Solve 10 problems correctly to get your car to the finish line!",
        problemsSolved: "Problems Solved: 0/10",
        startRace: "Start Race",
        submit: "Submit",
        targetGameTitle: "🎯 Target Practice",
        targetInstructions: "Hit the target by solving multiplication problems. Your accuracy will be tracked.",
        targetScore: "Hits: 0 | Accuracy: 0%",
        startPractice: "Start Practice",
        fire: "Fire! 🎯",
        challengeGameTitle: "🌟 Challenge Mode",
        challengeInstructions: "This is the hardest mode! Questions will come from all times tables 1-12. Wrong answers will break your streak.",
        challengeScore: "Streak: 0 | Best: 0",
        startChallenge: "Start Challenge",
        timeLeft: "Time:",
        seconds: "s",
        gameOver: "Game Over! Final Score:",
        playAgain: "Play Again",
        congratulations: "Congratulations! You matched all pairs! 🎉",
        raceComplete: "Race Complete! You won! 🏆",
        raceAgain: "Race Again",
        wrongAnswer: "Wrong answer! Your streak was",
        tryAgain: "Try again!",
        hits: "Hits:",
        accuracy: "Accuracy:",
        streak: "Streak:",
        best: "Best:"
    }
};

export let currentLanguage = 'hi';

export function setLanguage(lang) {
    currentLanguage = lang;
    document.documentElement.lang = lang;
}
